# Generated by Django 5.0.1 on 2024-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapsettings',
            old_name='group_search_base',
            new_name='group_search_base_dn',
        ),
        migrations.RenameField(
            model_name='ldapsettings',
            old_name='require_group',
            new_name='require_group_dn',
        ),
        migrations.RenameField(
            model_name='ldapsettings',
            old_name='user_search_base',
            new_name='user_search_base_dn',
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='user_search_filter',
            field=models.CharField(default='(sAMAccountName=%(user)s)', max_length=255),
        ),
    ]
