# Generated by Django 5.0.1 on 2024-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_group_search_base_ldapsettings_group_search_base_dn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsettings',
            name='group_search_filter',
            field=models.CharField(default='(objectClass=groupOfNames)', max_length=255),
        ),
    ]
